import globals from 'globals'

// Shared globals used across all files
const sharedGlobals = {
  // Browser
  ...globals.browser,
  // Supabase CDN
  supabase: 'readonly',
  // Core globals (state.js)
  db: 'writable',
  progId: 'writable',
  currentSection: 'writable',
  apqpTab: 'writable',
  npiTab: 'writable',
  capacityTab: 'writable',
  productionTab: 'writable',
  productDevelopmentTab: 'writable',
  operationsTab: 'writable',
  bomSubTab: 'writable',
  currentUser: 'writable',
  collapsedGroups: 'writable',
  meStartOffset: 'writable',
  insertOriginIdx: 'writable',
  bomPickTarget: 'writable',
  ctqPickTarget: 'writable',
  ctqPickSelected: 'writable',
  bomPickSelected: 'writable',
  bomPickFilter: 'writable',
  kitPickTarget: 'writable',
  kitPickSelected: 'writable',
  kitPickFilter: 'writable',
  saveTimer: 'writable',
  projectsPage: 'writable',
  projectsAllLoaded: 'writable',
  presenceMap: 'writable',
  GATE_DEFS: 'readonly',
  FAMILIES: 'readonly',
  BOM_TYPES: 'readonly',
  // Core globals (auth.js)
  supa: 'readonly',
  SUPA_URL: 'readonly',
  SUPA_KEY: 'readonly',
  doLogin: 'readonly',
  doLogout: 'readonly',
  launchApp: 'readonly',
  // Core globals (db.js)
  save: 'readonly',
  load: 'readonly',
  loadRemote: 'readonly',
  loadRemotePage: 'readonly',
  loadMoreProjects: 'readonly',
  subscribeProjectsGlobally: 'readonly',
  newProgTemplate: 'readonly',
  migrateprog: 'readonly',
  normalizeGateSelections: 'readonly',
  exportJSON: 'readonly',
  importJSON: 'readonly',
  getFamilies: 'readonly',
  getWorkAreaOptions: 'readonly',
  workAreasState: 'readonly',
  // Utils (helpers.js)
  esc: 'readonly',
  generateId: 'readonly',
  showModal: 'readonly',
  closeModal: 'readonly',
  emptyState: 'readonly',
  autoResizeAll: 'readonly',
  showToast: 'readonly',
  setupSmartDateInputs: 'readonly',
  // Utils (navigation.js)
  prog: 'readonly',
  render: 'readonly',
  navigate: 'readonly',
  navigateBack: 'readonly',
  parseHash: 'readonly',
  renderSection: 'readonly',
  goHome: 'readonly',
  goProjects: 'readonly',
  setApqpTab: 'readonly',
  initProgSelect: 'readonly',
  setSyncBadge: 'readonly',
  setProductDevelopmentTab: 'readonly',
  sortedPfd: 'readonly',
  calcRPN: 'readonly',
  getWeekNumber: 'readonly',
  createRealtimeSubscription: 'readonly',
  removeRealtimeSubscription: 'readonly',
  // app.js
  populateFamilySelects: 'readonly',
  familiesState: 'readonly',
  familiesDataInit: 'readonly',
  familyTemplatesDataInit: 'readonly',
  productsDataGetAll: 'readonly',
  productsDataInit: 'readonly',
  meDataInit: 'readonly',
  prodDataInit: 'readonly',
  prodCapDataInit: 'readonly',
  prodCapLoadUtilization: 'readonly',
  workAreasDataInit: 'readonly',
  // Chart.js
  Chart: 'readonly',
  // NPI namespace (global)
  npi: 'writable',
}

export default [
  {
    // Apply to all JavaScript files (excluding node_modules, tests, and config)
    files: ['**/*.js'],
    ignores: ['node_modules/**', 'tests/**', '*.config.js', 'scripts/**', '.claude/**', '.github/**', '.gemini/**'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: sharedGlobals,
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'warn',
      'eqeqeq': ['warn', 'always', { null: 'ignore' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
  {
    // NPI-specific configuration (stricter rules)
    files: ['portals/product-development/npi/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: {
        ...sharedGlobals,
        // NPI-specific globals
        RPN_HIGH: 'readonly',
        RPN_CRITICAL: 'readonly',
        PFMEA_SCORE_MIN: 'readonly',
        PFMEA_SCORE_MAX: 'readonly',
        APQP_TABS: 'readonly',
        BOM_TABS: 'readonly',
        GANTT_WEEKS: 'readonly',
        GANTT_ROLES: 'readonly',
        GANTT_SECTIONS: 'readonly',
        PLAN_COLOR: 'readonly',
        ACT_COLOR: 'readonly',
        npi: 'writable',
        renderRpnBurndown: 'readonly',
        renderPFMEA: 'readonly',
        gateAllSigned: 'readonly',
        refreshBomPickModal: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'warn',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
]
