import globals from 'globals'

export default [
  {
    files: ['portals/product-development/npi/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: {
        // Browser
        ...globals.browser,
        // Supabase CDN
        supabase: 'readonly',
        // Core globals (state.js)
        db: 'writable',
        progId: 'writable',
        currentSection: 'writable',
        apqpTab: 'writable',
        npiTab: 'writable',
        capacityTab: 'writable',
        productionTab: 'writable',
        productDevelopmentTab: 'writable',
        bomSubTab: 'writable',
        bomPartsRegisterView: 'writable',
        currentUser: 'writable',
        collapsedGroups: 'writable',
        meStartOffset: 'writable',
        insertOriginIdx: 'writable',
        bomPickTarget: 'writable',
        ctqPickTarget: 'writable',
        ctqPickSelected: 'writable',
        bomPickSelected: 'writable',
        bomPickFilter: 'writable',
        kitPickTarget: 'writable',
        kitPickSelected: 'writable',
        kitPickFilter: 'writable',
        saveTimer: 'writable',
        GATE_DEFS: 'readonly',
        FAMILIES: 'readonly',
        BOM_TYPES: 'readonly',
        SECTION_LABELS: 'readonly',
        // npi-constants.js
        RPN_HIGH: 'readonly',
        RPN_CRITICAL: 'readonly',
        PFMEA_SCORE_MIN: 'readonly',
        PFMEA_SCORE_MAX: 'readonly',
        APQP_TABS: 'readonly',
        BOM_TABS: 'readonly',
        GANTT_WEEKS: 'readonly',
        GANTT_ROLES: 'readonly',
        GANTT_SECTIONS: 'readonly',
        PLAN_COLOR: 'readonly',
        ACT_COLOR: 'readonly',
        // Core globals (auth.js)
        supa: 'readonly',
        SUPA_URL: 'readonly',
        SUPA_KEY: 'readonly',
        // Core globals (db.js)
        save: 'readonly',
        load: 'readonly',
        newProgTemplate: 'readonly',
        migrateprog: 'readonly',
        exportJSON: 'readonly',
        importJSON: 'readonly',
        getFamilies: 'readonly',
        getWorkAreaOptions: 'readonly',
        workAreasState: 'readonly',
        // Utils (helpers.js)
        esc: 'readonly',
        showModal: 'readonly',
        closeModal: 'readonly',
        emptyState: 'readonly',
        autoResizeAll: 'readonly',
        // Utils (navigation.js)
        prog: 'readonly',
        render: 'readonly',
        navigate: 'readonly',
        navigateBack: 'readonly',
        parseHash: 'readonly',
        renderSection: 'readonly',
        goHome: 'readonly',
        goProjects: 'readonly',
        setApqpTab: 'readonly',
        initProgSelect: 'readonly',
        setSyncBadge: 'readonly',
        setProductDevelopmentTab: 'readonly',
        sortedPfd: 'readonly',
        calcRPN: 'readonly',
        getWeekNumber: 'readonly',
        // npi.js namespace
        npi: 'writable',
        // Other portals that NPI calls cross-portal
        renderRpnBurndown: 'readonly',
        renderPFMEA: 'readonly',
        gateAllSigned: 'readonly',
        productsDataGetAll: 'readonly',
        refreshBomPickModal: 'readonly',
        // app.js
        populateFamilySelects: 'readonly',
        familiesState: 'readonly',
        familiesDataInit: 'readonly',
        familyTemplatesDataInit: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'warn',
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-var': 'warn',
      'prefer-const': 'warn',
    },
  },
]
